(function(){
 'use strict';
 const OWNER='74ab4fdf-3e78-49a7-8e23-e841408a184d',BUCKET='cardinal-visual-workspace';
 const $=id=>document.getElementById(id);
 const client=window.supa || window.supabase.createClient('https://yipslubcptjoarblzbpl.supabase.co','sb_publishable_aGsug3EBJjHX90BLKd5bLQ_zryUMqNZ',{auth:{storageKey:'cr-showroom-auth',persistSession:true,autoRefreshToken:true}});
 let editing=null, selected=[];
 const status=(id,text,error=false)=>{if($(id)){ $(id).textContent=text;$(id).classList.toggle('ws-error',error); }};
 async function session(){const {data,error}=await client.auth.getSession();if(error || !data.session || data.session.user.id!==OWNER) throw new Error('This workspace is private to the owner. Sign in to the Showroom with your owner account.');return data.session;}
 async function api(url,options={}){const s=await session();const r=await fetch(url,{...options,headers:{Authorization:'Bearer '+s.access_token,'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json();if(!r.ok)throw new Error(data.error||'The request could not be completed.');return data;}
 async function ensure(){await api('/api/visual-library?action=session',{method:'POST'});}
 function add(parent,tag,text,cls){const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;parent.append(el);return el;}
 async function notes(){if(!$('wsEntries'))return;const {entries}=await api('/api/library-records');$('wsEntries').replaceChildren();if(!entries.length)add($('wsEntries'),'p','No shared notes yet.');for(const e of entries){const a=add($('wsEntries'),'article','','ws-entry');add(a,'div',e.record_id+' · '+e.kind+' · '+e.recorded_by+' · '+new Date(e.updated_at).toLocaleString()+' · Revision '+e.revision,'ws-meta');add(a,'h3',e.title);add(a,'p',e.body);const edit=add(a,'button','Edit note');edit.type='button';edit.onclick=()=>{editing=e;for(const [id,key] of [['wsRecord','record_id'],['wsKind','kind'],['wsBy','recorded_by'],['wsTitle','title'],['wsBody','body']])$(id).value=e[key];$('wsCancel').hidden=false;$('wsSave').textContent='Save revision';$('wsTitle').focus();};const hist=add(a,'button','View revisions');hist.type='button';hist.onclick=async()=>{try{const r=await api('/api/library-records?history='+encodeURIComponent(e.id));const d=add(a,'details','');add(d,'summary','Saved revisions');for(const row of r.history){add(d,'h4','Revision '+row.revision);add(d,'p',row.snapshot.title+'\n'+row.snapshot.body);}d.open=true;hist.disabled=true;}catch(err){status('wsNoteStatus',err.message,true);}};}}
 function resetEdit(){editing=null;$('wsNoteForm').reset();$('wsCancel').hidden=true;$('wsSave').textContent='Save note';}
 $('wsNoteForm')?.addEventListener('submit',async ev=>{ev.preventDefault();$('wsSave').disabled=true;const data={record_id:$('wsRecord').value,kind:$('wsKind').value,recorded_by:$('wsBy').value,title:$('wsTitle').value,body:$('wsBody').value};if(editing)Object.assign(data,{id:editing.id,revision:editing.revision});try{await api('/api/library-records',{method:editing?'PATCH':'POST',body:JSON.stringify(data)});resetEdit();status('wsNoteStatus','Saved to the shared Library.');await notes();}catch(err){status('wsNoteStatus',err.message,true);}finally{$('wsSave').disabled=false;}});
 $('wsCancel')?.addEventListener('click',resetEdit);
 $('wsRefresh')?.addEventListener('click',()=>notes().catch(e=>status('wsNoteStatus',e.message,true)));
 $('wsFolder')?.addEventListener('change',ev=>{selected=[...ev.target.files];$('wsImport').disabled=!selected.length;status('wsImportStatus',selected.length+' files selected.');});
 const hash=async file=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');
 const mime=name=>({html:'text/html',css:'text/css',js:'text/javascript',mjs:'text/javascript',json:'application/json',svg:'image/svg+xml',glb:'model/gltf-binary',webp:'image/webp',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',pdf:'application/pdf',md:'text/plain',txt:'text/plain',zip:'application/zip'}[name.split('.').pop().toLowerCase()]||'application/octet-stream');
 $('wsImport')?.addEventListener('click',async()=>{
  $('wsImport').disabled=true;
  try{await session();const files=new Map(selected.map(f=>[f.webkitRelativePath.split('/').slice(1).join('/'),f]));const mf=files.get('workspace-manifest.json');if(!mf)throw new Error('Choose the prepared folder containing workspace-manifest.json.');const manifest=JSON.parse(await mf.text());if(!Array.isArray(manifest.files)||!manifest.id)throw new Error('This folder has no valid manifest.');
   for(const f of manifest.files){if(!/^(library-v60|experience-v054)\//.test(f.path)||f.path.split('/').some(x=>x==='..'||x==='.'||!x)||!files.has(f.path)||!/^\w{64}$/.test(f.sha256))throw new Error('The selected folder does not match its manifest.');}
   const old=await client.from('visual_library_imports').select('manifest').eq('id',manifest.id).maybeSingle();if(old.error)throw old.error;const done=old.data?.manifest?.completed||{};let count=0;const errors=[];const queue=[...manifest.files];$('wsProgress').max=queue.length;
   async function save(){const r=await client.from('visual_library_imports').upsert({id:manifest.id,manifest:{...manifest,completed:done},imported_at:new Date().toISOString()});if(r.error)throw r.error;}
   async function worker(){while(queue.length){const item=queue.shift();try{const file=files.get(item.path);if(done[item.path]!==item.sha256){if(await hash(file)!==item.sha256)throw new Error('File changed after preparation.');const r=await client.storage.from(BUCKET).upload(item.path,file,{upsert:true,contentType:mime(item.path),cacheControl:'0',metadata:{sha256:item.sha256}});if(r.error)throw r.error;done[item.path]=item.sha256;}}catch(e){errors.push(item.path+': '+e.message);}count++;$('wsProgress').value=count;status('wsImportStatus',count+' / '+manifest.files.length+' checked and synced.');}}
   await Promise.all([worker(),worker(),worker()]);await save();if(errors.length)throw new Error(errors.length+' files need a retry. '+errors.slice(0,3).join(' '));status('wsImportStatus','Sync complete: '+count+' files are in your private workspace.');
  }catch(e){status('wsImportStatus',e.message,true);}finally{$('wsImport').disabled=false;}
 });
 // Used by the migrated Library's existing document form. Upload directly to
 // private Storage so a PDF does not pass through a serverless body limit.
 window.CardinalLibraryUpload=async form=>{await session();const file=form.get('file');if(!(file instanceof File)||!file.size)throw new Error('Choose a file.');if(file.size>25*1024*1024)throw new Error('Choose a file smaller than 25 MB.');const key=crypto.randomUUID()+'/'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const r=await client.storage.from(BUCKET).upload('uploaded/'+key,file,{contentType:file.type||'application/octet-stream',upsert:false});if(r.error)throw r.error;const document={key,name:file.name,category:String(form.get('category')||'other'),manufacturer:String(form.get('manufacturer')||''),collection:String(form.get('collection')||''),documentType:file.type||'Document',size:file.size,uploadedAt:new Date().toISOString()};const meta=await client.from('visual_library_documents').insert({key,document});if(meta.error)throw meta.error;return {document};};
 async function start(){try{await ensure();status('wsStatus','Private to your owner account.');if($('wsContent'))$('wsContent').hidden=false;const dest=new URLSearchParams(location.search).get('open');if(dest==='library'||dest==='experience'){location.replace(dest==='library'?'/visual-library/library.html':'/cardinal-experience/index.html');return;}await notes();}catch(e){status('wsStatus',e.message,true);status('wsNoteStatus',e.message,true);}}
 client.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){fetch('/api/visual-library?action=session',{method:'DELETE'}).finally(()=>location.assign('/'));}});
 setInterval(()=>{if(document.visibilityState==='visible')ensure().catch(e=>status('wsStatus',e.message,true));},240000);
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')ensure().catch(e=>status('wsStatus',e.message,true));});
 start();
})();
