import test from 'node:test';
import assert from 'node:assert/strict';
import handler from '../api/visual-library.js';
import records from '../api/library-records.js';
import {OWNER,objectPath} from '../api/_visual-library.js';
function res(){return {code:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(c){this.code=c;return this;},json(b){this.body=b;return this;},send(b){this.body=b;return this;},end(){return this;},redirect(c,url){this.code=c;this.url=url;return this;}};}
test('private files reject anonymous access before any storage request',async()=>{let calls=0;global.fetch=async()=>{calls++;throw Error();};const r=res();await handler({headers:{},query:{area:'experience',asset:'index.html'},method:'GET'},r);assert.equal(r.code,401);assert.equal(calls,0);});
test('a signed-in staff account does not gain owner access',async()=>{global.fetch=async()=>new Response(JSON.stringify({id:'another-account'}));const r=res();await handler({headers:{authorization:'Bearer other'},query:{},method:'GET'},r);assert.equal(r.code,403);});
test('encoded and traversing paths are rejected',()=>{for(const p of ['../secret','a/../secret','a\\secret','a/%2e%2e/x','/absolute','a//b'])assert.equal(objectPath(p),null);assert.equal(objectPath('models/House 13.glb'),'models/House%2013.glb');});
test('cross-origin cookie session changes are rejected',async()=>{global.fetch=async()=>new Response(JSON.stringify({id:OWNER}));const r=res();await handler({headers:{authorization:'Bearer owner-origin',host:'showroom.test',origin:'https://elsewhere.test'},query:{action:'session'},method:'POST'},r);assert.equal(r.code,403);});
test('owner receives a private short-lived media redirect',async()=>{global.fetch=async url=>new Response(JSON.stringify(String(url).includes('/auth/v1/user')?{id:OWNER}:{signedURL:'/object/sign/private/model.glb?token=temporary'}));const r=res();await handler({headers:{authorization:'Bearer owner-media'},query:{area:'experience',asset:'model.glb'},method:'GET'},r);assert.equal(r.code,302);assert.match(r.headers['Cache-Control'],/no-store/);assert.match(r.url,/\/storage\/v1\/object\/sign\//);});
test('stale edits return conflict instead of overwriting a newer revision',async()=>{global.fetch=async url=>new Response(JSON.stringify(String(url).includes('/auth/v1/user')?{id:OWNER}:[]));const r=res();await records({headers:{authorization:'Bearer owner-edit',host:'showroom.test'},query:{},method:'PATCH',body:{id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',revision:1,record_id:'test',title:'Original',body:'Text'}},r);assert.equal(r.code,409);});
